PUT http://localhost:3003/api/blogs/66c34c9db32661bbbda6871d
Content-Type: application/json

{
    "title": "Fourth blog post",
    "author": "Isaac Newton",
    "url": "www.fullstackopen.com",
    "likes": 1
}